name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Generate and Populate .env file
        run: |
          echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} > .env
          echo APP_KEYS=${{ secrets.APP_KEYS }} >> .env
          echo DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }} >> .env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} >> .env
          echo TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} >> .env
          echo POSTGRES_USER=${{ secrets.DATABASE_NAME }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.DATABASE_NAME }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }} >> .env
          echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env
          echo AWS_BUCKET=${{ secrets.AWS_BUCKET }} >> .env

      - name: Copy .env file to remote server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_SSH_PORT }}
          source: ".env"
          target: "~/Apps/strapi"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.prod
          tags: mssalkhalifah/strapi:latest

  deploy:
    environment: production
    runs-on: ubuntu-latest

    needs: build-push

    steps:
      - name: deploy strapi
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_SERVER_SSH_PORT }}
          script: ./update-containers.sh strapi
